---
title: "Keren Omari-Baah"
output: html_document
---

**Hello, and welcome to my portfolio!**

I am currently pursuing an MSc in Data Science for Society and Business at Constructor University, Bremen, Germany (formerly Jacobs University Bremen). This repository showcases a collection of projects and reflects my growing expertise in data science, applied across various domains including marine science, healthcare, and finance.I’m really passionate about discovering how we can apply data science to areas beyond traditional business applications. While business analytics has its importance, I believe there’s so much more potential in using data science to drive revolutionary change in fields like sustainability, marine science, and beyond. Through this portfolio, you’ll find a collection of projects that reflect my curiosity and dedication to learning and using data for more than just insights.  

### Projects

#### Completed Projects

-   [Investigating Factors Influencing Salaries of Data Science Roles](Investigating factors that influence the salaries of data science roles.html)\
    Overview: Analyzed various factors that impact salary trends in the data science field in different countries.

-   [Analyzing Determinants of Academic Performance](Analyzing the Determinanats of Academic Performance.html)\
    Overview: Explored key factors influencing student success in two Portuguese high schools.

-   [Assessing The Compliance Of The 2021 Closed Season in Ghana Using AIS Data](Closed_Season_AIS.pdf)\
    Overview: Examined the adherence to Ghana's 2021 fishing closed season using Automatic Identification System (AIS) data to assess compliance and suggest improvements.

-   [A Comparative Analysis of Trends in Precision Medicine Trials](A Comparative  Analysis of Trends in Precision Medicine.html)\
    Overview: Examined cross-sectional data to compare trends between oncology and autoimmune diseases in precision medicine trials.

#### Ongoing Projects
 
 
-   [Combating birth control misinformation in a Digital Public Sphere:A policy brief on adressing myths and stigma of birthcontrol.](project5.html)\
    Overview: To analyze a reddit community on birth contol, identify the misinformation and to recommend a policy update to the Women's National Health Network to help stop the spread of misinformation.

-   [Predicting Customer Churn in the Banking Industry](project6.html)\
    Overview: Developing predictive models to identify potential customer churn in banking, enhancing customer retention strategies.

-   [The Role of Artificial Intelligence in Enhancing Breast Cancer Diagnosis and Personalized Treatment](project7.html)\
    Objective: Discussing the role of artificial intelligent (AI) in diagnosis and personalization in breast cancer treatment plans using a classification model to predict whether a tumor is benign or malignant.

-   [Artificial Intelligence in Higher Education](project8.html)\
    Objective: Discussing the use of artificial intelligent (AI) in higher education from the perspectives of key stakeholders, including university officials, students, educators, and AI service providers. The project aims to understand the impact of AI on teaching, learning, and administrative processes, while also addressing both the benefits and challenges faced by those involved in implementing AI solutions in educational settings.

-   [Applications of Artificial Intelligence in Higher Education](project9.html)\
    Objective: Researching the potential role of AI in developing teaching and learning support systems. The project will focus on exploring how AI can enhance personalized learning, provide adaptive teaching tools, and improve overall student engagement, ultimately laying the groundwork for the future creation of an AI-powered learning platform.

-   [The application of Artificial Intelligence in Climate Risk Prediction](project10.html)\
    Objective: Developing AI-based models for predicting climate risks, with a focus on identifying areas vulnerable to climate change. The project will explore AI's potential to analyze climate data and forecast environmental impacts, helping inform decision-making processes for mitigation and adaptation strategies.

**Note**: All ongoing projects are currently in the initialization stages. Each project has a designated repository that is be regularly updated with progress and developments. At this time, the full HTML files for these projects are not yet available, but updates will be added as the projects advance.




## Technical Skills

**Programming**: R, R Markdown,R Shiny, Python, SQL, SAS, NLP, HTML, JavaScript, CSS.\
**Technologies**: Git, Tableau, Microsoft Office Suite, RapidMiner.\

**Currently learning**: AWS, SPARQL, RDF, SAP.\

## Language Profienciency

**English** Fluent (Native)\
**German** A1 profiency\
**French** A1 profiency\

## Contact Information

Feel free to reach out for collaboration or questions regarding my projects.\
- [LinkedIn](https://www.linkedin.com/in/kerendankwah)\
- [Email](mailto:kerendankwah@gmail.com)\ 

